language: c
sudo: required
os:
  - linux
  - osx
env:
  global:
    - PACKAGE=ANSITerminal
  matrix:
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.04
cache:
  directories:
  - $HOME/.opam

install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh

notifications:
  email:
    - Christophe.Troestler@umons.ac.be
